import express from 'express';
import http from 'http';
import { WebSocketServer } from 'ws';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import ncm from 'NeteaseCloudMusicApi';
import crypto from 'crypto';
import { DatabaseSync } from 'node:sqlite';
import dns from 'dns';
import net from 'net';
import './gate-init.mjs';
